<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Review your Order_CartItem_productImage__DGtit</name>
   <tag></tag>
   <elementGuidId>436d12f1-2fc1-4735-aba1-b096b315247b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.CartItem_productImage__DGtit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/main/div/div/div/ul/li/div/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cdn11.bigcommerce.com/s-qfzerv205w/products/115/images/489/Hat-front-black__72990.1603748583.220.290.png?c=1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>CartItem_productImage__DGtit</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;Layout_root__3wCB1&quot;]/main[@class=&quot;fit&quot;]/div[@class=&quot;grid lg:grid-cols-12 w-full max-w-7xl mx-auto&quot;]/div[@class=&quot;lg:col-span-8&quot;]/div[@class=&quot;px-4 sm:px-6 flex-1&quot;]/ul[@class=&quot;py-6 space-y-6 sm:py-0 sm:space-y-0 sm:divide-y sm:divide-accent-2 border-b border-accent-2&quot;]/li[@class=&quot;CartItem_root__c20Bc&quot;]/div[@class=&quot;flex flex-row space-x-4 py-4&quot;]/div[@class=&quot;w-16 h-16 bg-violet relative overflow-hidden cursor-pointer z-0&quot;]/div[1]/img[@class=&quot;CartItem_productImage__DGtit&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div/div/div/ul/li/div/div/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://cdn11.bigcommerce.com/s-qfzerv205w/products/115/images/489/Hat-front-black__72990.1603748583.220.290.png?c=1')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
   </webElementXpaths>
</WebElementEntity>
